### ISSUE TITLE
Parola noua :D

### ISSUE THREAD

**Issue by croi900** [AfraIsNotAvailable/bcu_reservation#1]
parola: jesuslovesyou

bunul meu prieten afra scoate-ti credentialele din repo ca vin negrii si le fura (ca mine) 

![image](https://github.com/AfraIsNotAvailable/bcu_reservation/assets/43723625/8f5d5a01-a7b6-469e-8eb6-5045d59962f8)

**Comment by croi900** [comment]
ba muie
tu stii sa canti la ciatarna?

**Comment by AfraIsNotAvailable** [comment]
fuck

**Comment by AfraIsNotAvailable** [comment]
inca invat sa cant

**Comment by AfraIsNotAvailable** [comment]
ba da te gandeai sa mi furi locu la biblioteca?

**Comment by AfraIsNotAvailable** [comment]
also cum pl mea ai reusit sa schimbi parola pe site u ala parlit ca io n am gasit si am tot cautat ma jur
